### ISSUE TITLE
Add `getSubscriptionEndpoint` function

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool-lib#10]
Because subscription endpoint addresses are dynamic based on region, it would be helpful if you could expose a method to retrieve it. I will add a FR to the graphcool repo to add it to the System API, although it could also be constructed from just getting the project region from the System API.

**Comment by timsuchanek** [comment]
This is now added in the new `.graphcool.endpoints` context

**Comment by kbrandwijk** [comment]
Implemented how? They are not set automatically are they?
