### ISSUE TITLE
can't read property 'graphcool' of undefined

### ISSUE THREAD

**Issue by mkozhukharenko** [graphcool/graphcool-lib#4]
`event.context` is undefined when `graphcool-lib` is used in the lambda function (see this [line](https://github.com/graphcool/graphcool-lib/blob/master/src/index.ts#L99))

I was able to find `context` property in the event.body `JSON.parse(event.body).context`

Am I doing something wrong?

**Comment by mkozhukharenko** [comment]
Here is my proposal about changing a 'fromEvent' interface
```
fromEvent(options: GraphcoolOptions): Graphcool {}

export interface GraphcoolOptions {
  pat: string
  projectId: string

  serverEndpoint?: string // by default: 'https://api.graph.cool'
  pat?: string
}
```

**Comment by kbrandwijk** [comment]
`fromEvent()` is really a shorthand specifically designed for use in SE's. There's also a normal constructor: https://github.com/graphcool/graphcool-lib/blob/master/src/index.ts#L10 which should be suitable for all other needs as far as my use cases are concerned...

**Comment by mkozhukharenko** [comment]
thanks @kbrandwijk , you helped a lot!
